apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: destail-destination-rule
spec:
  host: details.default.svc.cluster.local  
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL